=begin
#API v1

#DocSpring is a service that helps you fill out and sign PDF templates.

OpenAPI spec version: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DocSpring::UpdateTemplateData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UpdateTemplateData' do
  before do
    # run before each test
    @instance = DocSpring::UpdateTemplateData.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UpdateTemplateData' do
    it 'should create an instance of UpdateTemplateData' do
      expect(@instance).to be_instance_of(DocSpring::UpdateTemplateData)
    end
  end
  describe 'test attribute "template"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
